/** Auto-generated by scripts/export-city-atlas-seed.py — do not edit by hand. */

export type CityAtlasSeedCity = { modernName: string; ancientName: string };
export type CityAtlasSeedGroup = {
  name: string;
  fullName: string;
  sortOrder: number;
  macroRegionId: string;
  cities: CityAtlasSeedCity[];
};

export const CITY_ATLAS_SEED: CityAtlasSeedGroup[] = 
[
  {
    "name": "北京",
    "fullName": "北京市",
    "sortOrder": 0,
    "macroRegionId": "huabei",
    "cities": [
      {
        "modernName": "北京市",
        "ancientName": "燕京"
      }
    ]
  },
  {
    "name": "天津",
    "fullName": "天津市",
    "sortOrder": 1,
    "macroRegionId": "huabei",
    "cities": [
      {
        "modernName": "天津市",
        "ancientName": "津门"
      }
    ]
  },
  {
    "name": "河北",
    "fullName": "河北省",
    "sortOrder": 2,
    "macroRegionId": "huabei",
    "cities": [
      {
        "modernName": "石家庄市",
        "ancientName": "石门"
      },
      {
        "modernName": "唐山市",
        "ancientName": "滦州"
      },
      {
        "modernName": "秦皇岛市",
        "ancientName": "临渝"
      },
      {
        "modernName": "邯郸市",
        "ancientName": "邯郸"
      },
      {
        "modernName": "邢台市",
        "ancientName": "邢州"
      },
      {
        "modernName": "保定市",
        "ancientName": "上谷"
      },
      {
        "modernName": "张家口市",
        "ancientName": "宣府"
      },
      {
        "modernName": "承德市",
        "ancientName": "热河"
      },
      {
        "modernName": "沧州市",
        "ancientName": "渤海"
      },
      {
        "modernName": "廊坊市",
        "ancientName": "安次"
      },
      {
        "modernName": "衡水市",
        "ancientName": "冀州"
      }
    ]
  },
  {
    "name": "山西",
    "fullName": "山西省",
    "sortOrder": 3,
    "macroRegionId": "huabei",
    "cities": [
      {
        "modernName": "太原市",
        "ancientName": "晋阳"
      },
      {
        "modernName": "大同市",
        "ancientName": "平城"
      },
      {
        "modernName": "阳泉市",
        "ancientName": "漾泉"
      },
      {
        "modernName": "长治市",
        "ancientName": "潞州"
      },
      {
        "modernName": "晋城市",
        "ancientName": "泽州"
      },
      {
        "modernName": "朔州市",
        "ancientName": "马邑"
      },
      {
        "modernName": "晋中市",
        "ancientName": "榆次"
      },
      {
        "modernName": "运城市",
        "ancientName": "河东"
      },
      {
        "modernName": "忻州市",
        "ancientName": "秀容"
      },
      {
        "modernName": "临汾市",
        "ancientName": "平阳"
      },
      {
        "modernName": "吕梁市",
        "ancientName": "离石"
      }
    ]
  },
  {
    "name": "内蒙古",
    "fullName": "内蒙古自治区",
    "sortOrder": 4,
    "macroRegionId": "huabei",
    "cities": [
      {
        "modernName": "呼和浩特市",
        "ancientName": "云中"
      },
      {
        "modernName": "包头市",
        "ancientName": "九原"
      },
      {
        "modernName": "乌海市",
        "ancientName": "乌达"
      },
      {
        "modernName": "赤峰市",
        "ancientName": "昭乌达"
      },
      {
        "modernName": "通辽市",
        "ancientName": "科尔沁"
      },
      {
        "modernName": "鄂尔多斯市",
        "ancientName": "东胜"
      },
      {
        "modernName": "呼伦贝尔市",
        "ancientName": "海拉尔"
      },
      {
        "modernName": "巴彦淖尔市",
        "ancientName": "临河"
      },
      {
        "modernName": "乌兰察布市",
        "ancientName": "集宁"
      },
      {
        "modernName": "兴安盟",
        "ancientName": "嫩江"
      },
      {
        "modernName": "锡林郭勒盟",
        "ancientName": "锡林浩特"
      },
      {
        "modernName": "阿拉善盟",
        "ancientName": "额济纳"
      }
    ]
  },
  {
    "name": "辽宁",
    "fullName": "辽宁省",
    "sortOrder": 5,
    "macroRegionId": "dongbei",
    "cities": [
      {
        "modernName": "沈阳市",
        "ancientName": "盛京"
      },
      {
        "modernName": "大连市",
        "ancientName": "金州"
      },
      {
        "modernName": "鞍山市",
        "ancientName": "鞍山"
      },
      {
        "modernName": "抚顺市",
        "ancientName": "抚顺"
      },
      {
        "modernName": "本溪市",
        "ancientName": "本溪"
      },
      {
        "modernName": "丹东市",
        "ancientName": "安东"
      },
      {
        "modernName": "锦州市",
        "ancientName": "锦州"
      },
      {
        "modernName": "营口市",
        "ancientName": "营口"
      },
      {
        "modernName": "阜新市",
        "ancientName": "海州"
      },
      {
        "modernName": "辽阳市",
        "ancientName": "襄平"
      },
      {
        "modernName": "盘锦市",
        "ancientName": "盘山"
      },
      {
        "modernName": "铁岭市",
        "ancientName": "银州"
      },
      {
        "modernName": "朝阳市",
        "ancientName": "龙城"
      },
      {
        "modernName": "葫芦岛市",
        "ancientName": "宁远"
      }
    ]
  },
  {
    "name": "吉林",
    "fullName": "吉林省",
    "sortOrder": 6,
    "macroRegionId": "dongbei",
    "cities": [
      {
        "modernName": "长春市",
        "ancientName": "长春"
      },
      {
        "modernName": "吉林市",
        "ancientName": "吉林乌拉"
      },
      {
        "modernName": "四平市",
        "ancientName": "四平"
      },
      {
        "modernName": "辽源市",
        "ancientName": "西安"
      },
      {
        "modernName": "通化市",
        "ancientName": "通化"
      },
      {
        "modernName": "白山市",
        "ancientName": "白山"
      },
      {
        "modernName": "松原市",
        "ancientName": "郭尔罗斯"
      },
      {
        "modernName": "白城市",
        "ancientName": "白城"
      },
      {
        "modernName": "延边朝鲜族自治州",
        "ancientName": "延吉"
      }
    ]
  },
  {
    "name": "黑龙江",
    "fullName": "黑龙江省",
    "sortOrder": 7,
    "macroRegionId": "dongbei",
    "cities": [
      {
        "modernName": "哈尔滨市",
        "ancientName": "阿勒锦"
      },
      {
        "modernName": "齐齐哈尔市",
        "ancientName": "卜奎"
      },
      {
        "modernName": "鸡西市",
        "ancientName": "鸡西"
      },
      {
        "modernName": "鹤岗市",
        "ancientName": "鹤岗"
      },
      {
        "modernName": "双鸭山市",
        "ancientName": "双鸭山"
      },
      {
        "modernName": "大庆市",
        "ancientName": "肇州"
      },
      {
        "modernName": "伊春市",
        "ancientName": "伊春"
      },
      {
        "modernName": "佳木斯市",
        "ancientName": "佳木斯"
      },
      {
        "modernName": "七台河市",
        "ancientName": "勃利"
      },
      {
        "modernName": "牡丹江市",
        "ancientName": "宁古塔"
      },
      {
        "modernName": "黑河市",
        "ancientName": "瑷珲"
      },
      {
        "modernName": "绥化市",
        "ancientName": "绥化"
      },
      {
        "modernName": "大兴安岭地区",
        "ancientName": "加格达奇"
      }
    ]
  },
  {
    "name": "上海",
    "fullName": "上海市",
    "sortOrder": 8,
    "macroRegionId": "huadong",
    "cities": [
      {
        "modernName": "上海市",
        "ancientName": "申城"
      }
    ]
  },
  {
    "name": "江苏",
    "fullName": "江苏省",
    "sortOrder": 9,
    "macroRegionId": "huadong",
    "cities": [
      {
        "modernName": "南京市",
        "ancientName": "金陵"
      },
      {
        "modernName": "无锡市",
        "ancientName": "梁溪"
      },
      {
        "modernName": "徐州市",
        "ancientName": "彭城"
      },
      {
        "modernName": "常州市",
        "ancientName": "毗陵"
      },
      {
        "modernName": "苏州市",
        "ancientName": "姑苏"
      },
      {
        "modernName": "南通市",
        "ancientName": "通州"
      },
      {
        "modernName": "连云港市",
        "ancientName": "海州"
      },
      {
        "modernName": "淮安市",
        "ancientName": "淮阴"
      },
      {
        "modernName": "盐城市",
        "ancientName": "盐渎"
      },
      {
        "modernName": "扬州市",
        "ancientName": "广陵"
      },
      {
        "modernName": "镇江市",
        "ancientName": "京口"
      },
      {
        "modernName": "泰州市",
        "ancientName": "海陵"
      },
      {
        "modernName": "宿迁市",
        "ancientName": "宿豫"
      }
    ]
  },
  {
    "name": "浙江",
    "fullName": "浙江省",
    "sortOrder": 10,
    "macroRegionId": "huadong",
    "cities": [
      {
        "modernName": "杭州市",
        "ancientName": "临安"
      },
      {
        "modernName": "宁波市",
        "ancientName": "明州"
      },
      {
        "modernName": "温州市",
        "ancientName": "永嘉"
      },
      {
        "modernName": "嘉兴市",
        "ancientName": "禾城"
      },
      {
        "modernName": "湖州市",
        "ancientName": "吴兴"
      },
      {
        "modernName": "绍兴市",
        "ancientName": "会稽"
      },
      {
        "modernName": "金华市",
        "ancientName": "婺州"
      },
      {
        "modernName": "衢州市",
        "ancientName": "衢州"
      },
      {
        "modernName": "舟山市",
        "ancientName": "定海"
      },
      {
        "modernName": "台州市",
        "ancientName": "临海"
      },
      {
        "modernName": "丽水市",
        "ancientName": "处州"
      }
    ]
  },
  {
    "name": "安徽",
    "fullName": "安徽省",
    "sortOrder": 11,
    "macroRegionId": "huadong",
    "cities": [
      {
        "modernName": "合肥市",
        "ancientName": "庐州"
      },
      {
        "modernName": "芜湖市",
        "ancientName": "芜湖"
      },
      {
        "modernName": "蚌埠市",
        "ancientName": "蚌埠"
      },
      {
        "modernName": "淮南市",
        "ancientName": "寿春"
      },
      {
        "modernName": "马鞍山市",
        "ancientName": "当涂"
      },
      {
        "modernName": "淮北市",
        "ancientName": "相城"
      },
      {
        "modernName": "铜陵市",
        "ancientName": "铜陵"
      },
      {
        "modernName": "安庆市",
        "ancientName": "安庆"
      },
      {
        "modernName": "黄山市",
        "ancientName": "徽州"
      },
      {
        "modernName": "滁州市",
        "ancientName": "滁州"
      },
      {
        "modernName": "阜阳市",
        "ancientName": "颍州"
      },
      {
        "modernName": "宿州市",
        "ancientName": "宿州"
      },
      {
        "modernName": "六安市",
        "ancientName": "六安"
      },
      {
        "modernName": "亳州市",
        "ancientName": "亳州"
      },
      {
        "modernName": "池州市",
        "ancientName": "池州"
      },
      {
        "modernName": "宣城市",
        "ancientName": "宣城"
      }
    ]
  },
  {
    "name": "福建",
    "fullName": "福建省",
    "sortOrder": 12,
    "macroRegionId": "huadong",
    "cities": [
      {
        "modernName": "福州市",
        "ancientName": "闽都"
      },
      {
        "modernName": "厦门市",
        "ancientName": "鹭岛"
      },
      {
        "modernName": "莆田市",
        "ancientName": "莆田"
      },
      {
        "modernName": "三明市",
        "ancientName": "三明"
      },
      {
        "modernName": "泉州市",
        "ancientName": "刺桐"
      },
      {
        "modernName": "漳州市",
        "ancientName": "漳州"
      },
      {
        "modernName": "南平市",
        "ancientName": "建州"
      },
      {
        "modernName": "龙岩市",
        "ancientName": "龙岩"
      },
      {
        "modernName": "宁德市",
        "ancientName": "宁德"
      }
    ]
  },
  {
    "name": "江西",
    "fullName": "江西省",
    "sortOrder": 13,
    "macroRegionId": "huadong",
    "cities": [
      {
        "modernName": "南昌市",
        "ancientName": "洪都"
      },
      {
        "modernName": "景德镇市",
        "ancientName": "昌南"
      },
      {
        "modernName": "萍乡市",
        "ancientName": "萍乡"
      },
      {
        "modernName": "九江市",
        "ancientName": "浔阳"
      },
      {
        "modernName": "新余市",
        "ancientName": "新喻"
      },
      {
        "modernName": "鹰潭市",
        "ancientName": "鹰潭"
      },
      {
        "modernName": "赣州市",
        "ancientName": "虔州"
      },
      {
        "modernName": "吉安市",
        "ancientName": "庐陵"
      },
      {
        "modernName": "宜春市",
        "ancientName": "袁州"
      },
      {
        "modernName": "抚州市",
        "ancientName": "临川"
      },
      {
        "modernName": "上饶市",
        "ancientName": "上饶"
      }
    ]
  },
  {
    "name": "山东",
    "fullName": "山东省",
    "sortOrder": 14,
    "macroRegionId": "huadong",
    "cities": [
      {
        "modernName": "济南市",
        "ancientName": "历下"
      },
      {
        "modernName": "青岛市",
        "ancientName": "胶澳"
      },
      {
        "modernName": "淄博市",
        "ancientName": "临淄"
      },
      {
        "modernName": "枣庄市",
        "ancientName": "峄阳"
      },
      {
        "modernName": "东营市",
        "ancientName": "乐安"
      },
      {
        "modernName": "烟台市",
        "ancientName": "登州"
      },
      {
        "modernName": "潍坊市",
        "ancientName": "潍县"
      },
      {
        "modernName": "济宁市",
        "ancientName": "任城"
      },
      {
        "modernName": "泰安市",
        "ancientName": "泰山"
      },
      {
        "modernName": "威海市",
        "ancientName": "文登"
      },
      {
        "modernName": "日照市",
        "ancientName": "莒县"
      },
      {
        "modernName": "临沂市",
        "ancientName": "琅琊"
      },
      {
        "modernName": "德州市",
        "ancientName": "安德"
      },
      {
        "modernName": "聊城市",
        "ancientName": "东昌"
      },
      {
        "modernName": "滨州市",
        "ancientName": "棣州"
      },
      {
        "modernName": "菏泽市",
        "ancientName": "曹州"
      }
    ]
  },
  {
    "name": "河南",
    "fullName": "河南省",
    "sortOrder": 15,
    "macroRegionId": "huazhong",
    "cities": [
      {
        "modernName": "郑州市",
        "ancientName": "商都"
      },
      {
        "modernName": "开封市",
        "ancientName": "汴梁"
      },
      {
        "modernName": "洛阳市",
        "ancientName": "神都"
      },
      {
        "modernName": "平顶山市",
        "ancientName": "鹰城"
      },
      {
        "modernName": "安阳市",
        "ancientName": "殷墟"
      },
      {
        "modernName": "鹤壁市",
        "ancientName": "鹤壁"
      },
      {
        "modernName": "新乡市",
        "ancientName": "牧野"
      },
      {
        "modernName": "焦作市",
        "ancientName": "怀庆"
      },
      {
        "modernName": "濮阳市",
        "ancientName": "濮阳"
      },
      {
        "modernName": "许昌市",
        "ancientName": "许都"
      },
      {
        "modernName": "漯河市",
        "ancientName": "漯河"
      },
      {
        "modernName": "三门峡市",
        "ancientName": "陕州"
      },
      {
        "modernName": "南阳市",
        "ancientName": "宛城"
      },
      {
        "modernName": "商丘市",
        "ancientName": "宋州"
      },
      {
        "modernName": "信阳市",
        "ancientName": "义阳"
      },
      {
        "modernName": "周口市",
        "ancientName": "陈州"
      },
      {
        "modernName": "驻马店市",
        "ancientName": "汝宁"
      }
    ]
  },
  {
    "name": "湖北",
    "fullName": "湖北省",
    "sortOrder": 16,
    "macroRegionId": "huazhong",
    "cities": [
      {
        "modernName": "武汉市",
        "ancientName": "江城"
      },
      {
        "modernName": "黄石市",
        "ancientName": "黄石"
      },
      {
        "modernName": "十堰市",
        "ancientName": "郧阳"
      },
      {
        "modernName": "宜昌市",
        "ancientName": "夷陵"
      },
      {
        "modernName": "襄阳市",
        "ancientName": "襄阳"
      },
      {
        "modernName": "鄂州市",
        "ancientName": "鄂州"
      },
      {
        "modernName": "荆门市",
        "ancientName": "荆门"
      },
      {
        "modernName": "孝感市",
        "ancientName": "孝感"
      },
      {
        "modernName": "荆州市",
        "ancientName": "江陵"
      },
      {
        "modernName": "黄冈市",
        "ancientName": "黄州"
      },
      {
        "modernName": "咸宁市",
        "ancientName": "咸宁"
      },
      {
        "modernName": "随州市",
        "ancientName": "随州"
      },
      {
        "modernName": "恩施土家族苗族自治州",
        "ancientName": "施州"
      }
    ]
  },
  {
    "name": "湖南",
    "fullName": "湖南省",
    "sortOrder": 17,
    "macroRegionId": "huazhong",
    "cities": [
      {
        "modernName": "长沙市",
        "ancientName": "潭州"
      },
      {
        "modernName": "株洲市",
        "ancientName": "株洲"
      },
      {
        "modernName": "湘潭市",
        "ancientName": "湘潭"
      },
      {
        "modernName": "衡阳市",
        "ancientName": "衡阳"
      },
      {
        "modernName": "邵阳市",
        "ancientName": "邵阳"
      },
      {
        "modernName": "岳阳市",
        "ancientName": "巴陵"
      },
      {
        "modernName": "常德市",
        "ancientName": "武陵"
      },
      {
        "modernName": "张家界市",
        "ancientName": "大庸"
      },
      {
        "modernName": "益阳市",
        "ancientName": "益阳"
      },
      {
        "modernName": "郴州市",
        "ancientName": "郴州"
      },
      {
        "modernName": "永州市",
        "ancientName": "零陵"
      },
      {
        "modernName": "怀化市",
        "ancientName": "鹤城"
      },
      {
        "modernName": "娄底市",
        "ancientName": "娄底"
      },
      {
        "modernName": "湘西土家族苗族自治州",
        "ancientName": "溪州"
      }
    ]
  },
  {
    "name": "广东",
    "fullName": "广东省",
    "sortOrder": 18,
    "macroRegionId": "huanan",
    "cities": [
      {
        "modernName": "广州市",
        "ancientName": "羊城"
      },
      {
        "modernName": "韶关市",
        "ancientName": "韶州"
      },
      {
        "modernName": "深圳市",
        "ancientName": "鹏城"
      },
      {
        "modernName": "珠海市",
        "ancientName": "香洲"
      },
      {
        "modernName": "汕头市",
        "ancientName": "汕头"
      },
      {
        "modernName": "佛山市",
        "ancientName": "佛山"
      },
      {
        "modernName": "江门市",
        "ancientName": "江门"
      },
      {
        "modernName": "湛江市",
        "ancientName": "雷州"
      },
      {
        "modernName": "茂名市",
        "ancientName": "茂名"
      },
      {
        "modernName": "肇庆市",
        "ancientName": "端州"
      },
      {
        "modernName": "惠州市",
        "ancientName": "惠州"
      },
      {
        "modernName": "梅州市",
        "ancientName": "梅州"
      },
      {
        "modernName": "汕尾市",
        "ancientName": "海丰"
      },
      {
        "modernName": "河源市",
        "ancientName": "河源"
      },
      {
        "modernName": "阳江市",
        "ancientName": "阳江"
      },
      {
        "modernName": "清远市",
        "ancientName": "清远"
      },
      {
        "modernName": "东莞市",
        "ancientName": "莞城"
      },
      {
        "modernName": "中山市",
        "ancientName": "香山"
      },
      {
        "modernName": "潮州市",
        "ancientName": "潮州"
      },
      {
        "modernName": "揭阳市",
        "ancientName": "揭阳"
      },
      {
        "modernName": "云浮市",
        "ancientName": "云浮"
      }
    ]
  },
  {
    "name": "广西",
    "fullName": "广西壮族自治区",
    "sortOrder": 19,
    "macroRegionId": "huanan",
    "cities": [
      {
        "modernName": "南宁市",
        "ancientName": "邕州"
      },
      {
        "modernName": "柳州市",
        "ancientName": "柳州"
      },
      {
        "modernName": "桂林市",
        "ancientName": "桂林"
      },
      {
        "modernName": "梧州市",
        "ancientName": "梧州"
      },
      {
        "modernName": "北海市",
        "ancientName": "合浦"
      },
      {
        "modernName": "防城港市",
        "ancientName": "防城"
      },
      {
        "modernName": "钦州市",
        "ancientName": "钦州"
      },
      {
        "modernName": "贵港市",
        "ancientName": "贵县"
      },
      {
        "modernName": "玉林市",
        "ancientName": "玉林"
      },
      {
        "modernName": "百色市",
        "ancientName": "百色"
      },
      {
        "modernName": "贺州市",
        "ancientName": "贺州"
      },
      {
        "modernName": "河池市",
        "ancientName": "宜州"
      },
      {
        "modernName": "来宾市",
        "ancientName": "来宾"
      },
      {
        "modernName": "崇左市",
        "ancientName": "崇左"
      }
    ]
  },
  {
    "name": "海南",
    "fullName": "海南省",
    "sortOrder": 20,
    "macroRegionId": "huanan",
    "cities": [
      {
        "modernName": "海口市",
        "ancientName": "琼州"
      },
      {
        "modernName": "三亚市",
        "ancientName": "崖州"
      },
      {
        "modernName": "三沙市",
        "ancientName": "西沙"
      },
      {
        "modernName": "儋州市",
        "ancientName": "儋州"
      }
    ]
  },
  {
    "name": "重庆",
    "fullName": "重庆市",
    "sortOrder": 21,
    "macroRegionId": "xinan",
    "cities": [
      {
        "modernName": "重庆市",
        "ancientName": "渝州"
      }
    ]
  },
  {
    "name": "四川",
    "fullName": "四川省",
    "sortOrder": 22,
    "macroRegionId": "xinan",
    "cities": [
      {
        "modernName": "成都市",
        "ancientName": "锦官城"
      },
      {
        "modernName": "自贡市",
        "ancientName": "自流井"
      },
      {
        "modernName": "攀枝花市",
        "ancientName": "攀枝花"
      },
      {
        "modernName": "泸州市",
        "ancientName": "泸州"
      },
      {
        "modernName": "德阳市",
        "ancientName": "德阳"
      },
      {
        "modernName": "绵阳市",
        "ancientName": "涪县"
      },
      {
        "modernName": "广元市",
        "ancientName": "利州"
      },
      {
        "modernName": "遂宁市",
        "ancientName": "遂宁"
      },
      {
        "modernName": "内江市",
        "ancientName": "内江"
      },
      {
        "modernName": "乐山市",
        "ancientName": "嘉州"
      },
      {
        "modernName": "南充市",
        "ancientName": "顺庆"
      },
      {
        "modernName": "眉山市",
        "ancientName": "眉山"
      },
      {
        "modernName": "宜宾市",
        "ancientName": "戎州"
      },
      {
        "modernName": "广安市",
        "ancientName": "广安"
      },
      {
        "modernName": "达州市",
        "ancientName": "达州"
      },
      {
        "modernName": "雅安市",
        "ancientName": "雅州"
      },
      {
        "modernName": "巴中市",
        "ancientName": "巴州"
      },
      {
        "modernName": "资阳市",
        "ancientName": "资阳"
      },
      {
        "modernName": "阿坝藏族羌族自治州",
        "ancientName": "马尔康"
      },
      {
        "modernName": "甘孜藏族自治州",
        "ancientName": "康定"
      },
      {
        "modernName": "凉山彝族自治州",
        "ancientName": "西昌"
      }
    ]
  },
  {
    "name": "贵州",
    "fullName": "贵州省",
    "sortOrder": 23,
    "macroRegionId": "xinan",
    "cities": [
      {
        "modernName": "贵阳市",
        "ancientName": "筑城"
      },
      {
        "modernName": "六盘水市",
        "ancientName": "六盘水"
      },
      {
        "modernName": "遵义市",
        "ancientName": "播州"
      },
      {
        "modernName": "安顺市",
        "ancientName": "安顺"
      },
      {
        "modernName": "毕节市",
        "ancientName": "毕节"
      },
      {
        "modernName": "铜仁市",
        "ancientName": "铜仁"
      },
      {
        "modernName": "黔西南布依族苗族自治州",
        "ancientName": "兴义"
      },
      {
        "modernName": "黔东南苗族侗族自治州",
        "ancientName": "凯里"
      },
      {
        "modernName": "黔南布依族苗族自治州",
        "ancientName": "都匀"
      }
    ]
  },
  {
    "name": "云南",
    "fullName": "云南省",
    "sortOrder": 24,
    "macroRegionId": "xinan",
    "cities": [
      {
        "modernName": "昆明市",
        "ancientName": "春城"
      },
      {
        "modernName": "曲靖市",
        "ancientName": "曲靖"
      },
      {
        "modernName": "玉溪市",
        "ancientName": "玉溪"
      },
      {
        "modernName": "保山市",
        "ancientName": "永昌"
      },
      {
        "modernName": "昭通市",
        "ancientName": "昭通"
      },
      {
        "modernName": "丽江市",
        "ancientName": "丽江"
      },
      {
        "modernName": "普洱市",
        "ancientName": "思茅"
      },
      {
        "modernName": "临沧市",
        "ancientName": "缅宁"
      },
      {
        "modernName": "楚雄彝族自治州",
        "ancientName": "楚雄"
      },
      {
        "modernName": "红河哈尼族彝族自治州",
        "ancientName": "蒙自"
      },
      {
        "modernName": "文山壮族苗族自治州",
        "ancientName": "文山"
      },
      {
        "modernName": "西双版纳傣族自治州",
        "ancientName": "勐泐"
      },
      {
        "modernName": "大理白族自治州",
        "ancientName": "大理"
      },
      {
        "modernName": "德宏傣族景颇族自治州",
        "ancientName": "芒市"
      },
      {
        "modernName": "怒江傈僳族自治州",
        "ancientName": "泸水"
      },
      {
        "modernName": "迪庆藏族自治州",
        "ancientName": "香格里拉"
      }
    ]
  },
  {
    "name": "西藏",
    "fullName": "西藏自治区",
    "sortOrder": 25,
    "macroRegionId": "xinan",
    "cities": [
      {
        "modernName": "拉萨市",
        "ancientName": "逻些"
      },
      {
        "modernName": "日喀则市",
        "ancientName": "后藏"
      },
      {
        "modernName": "昌都市",
        "ancientName": "昌都"
      },
      {
        "modernName": "林芝市",
        "ancientName": "林芝"
      },
      {
        "modernName": "山南市",
        "ancientName": "山南"
      },
      {
        "modernName": "那曲市",
        "ancientName": "那曲"
      },
      {
        "modernName": "阿里地区",
        "ancientName": "象雄"
      }
    ]
  },
  {
    "name": "陕西",
    "fullName": "陕西省",
    "sortOrder": 26,
    "macroRegionId": "xibei",
    "cities": [
      {
        "modernName": "西安市",
        "ancientName": "长安"
      },
      {
        "modernName": "铜川市",
        "ancientName": "同官"
      },
      {
        "modernName": "宝鸡市",
        "ancientName": "陈仓"
      },
      {
        "modernName": "咸阳市",
        "ancientName": "咸阳"
      },
      {
        "modernName": "渭南市",
        "ancientName": "华州"
      },
      {
        "modernName": "延安市",
        "ancientName": "延州"
      },
      {
        "modernName": "汉中市",
        "ancientName": "南郑"
      },
      {
        "modernName": "榆林市",
        "ancientName": "榆林"
      },
      {
        "modernName": "安康市",
        "ancientName": "安康"
      },
      {
        "modernName": "商洛市",
        "ancientName": "商州"
      }
    ]
  },
  {
    "name": "甘肃",
    "fullName": "甘肃省",
    "sortOrder": 27,
    "macroRegionId": "xibei",
    "cities": [
      {
        "modernName": "兰州市",
        "ancientName": "金城"
      },
      {
        "modernName": "嘉峪关市",
        "ancientName": "嘉峪关"
      },
      {
        "modernName": "金昌市",
        "ancientName": "金昌"
      },
      {
        "modernName": "白银市",
        "ancientName": "白银"
      },
      {
        "modernName": "天水市",
        "ancientName": "秦州"
      },
      {
        "modernName": "武威市",
        "ancientName": "凉州"
      },
      {
        "modernName": "张掖市",
        "ancientName": "甘州"
      },
      {
        "modernName": "平凉市",
        "ancientName": "平凉"
      },
      {
        "modernName": "酒泉市",
        "ancientName": "肃州"
      },
      {
        "modernName": "庆阳市",
        "ancientName": "庆阳"
      },
      {
        "modernName": "定西市",
        "ancientName": "定西"
      },
      {
        "modernName": "陇南市",
        "ancientName": "陇南"
      },
      {
        "modernName": "临夏回族自治州",
        "ancientName": "河州"
      },
      {
        "modernName": "甘南藏族自治州",
        "ancientName": "甘南"
      }
    ]
  },
  {
    "name": "青海",
    "fullName": "青海省",
    "sortOrder": 28,
    "macroRegionId": "xibei",
    "cities": [
      {
        "modernName": "西宁市",
        "ancientName": "鄯州"
      },
      {
        "modernName": "海东市",
        "ancientName": "乐都"
      },
      {
        "modernName": "海北藏族自治州",
        "ancientName": "海晏"
      },
      {
        "modernName": "黄南藏族自治州",
        "ancientName": "同仁"
      },
      {
        "modernName": "海南藏族自治州",
        "ancientName": "共和"
      },
      {
        "modernName": "果洛藏族自治州",
        "ancientName": "果洛"
      },
      {
        "modernName": "玉树藏族自治州",
        "ancientName": "玉树"
      },
      {
        "modernName": "海西蒙古族藏族自治州",
        "ancientName": "柴达木"
      }
    ]
  },
  {
    "name": "宁夏",
    "fullName": "宁夏回族自治区",
    "sortOrder": 29,
    "macroRegionId": "xibei",
    "cities": [
      {
        "modernName": "银川市",
        "ancientName": "兴庆府"
      },
      {
        "modernName": "石嘴山市",
        "ancientName": "石嘴山"
      },
      {
        "modernName": "吴忠市",
        "ancientName": "灵州"
      },
      {
        "modernName": "固原市",
        "ancientName": "原州"
      },
      {
        "modernName": "中卫市",
        "ancientName": "中卫"
      }
    ]
  },
  {
    "name": "新疆",
    "fullName": "新疆维吾尔自治区",
    "sortOrder": 30,
    "macroRegionId": "xibei",
    "cities": [
      {
        "modernName": "乌鲁木齐市",
        "ancientName": "迪化"
      },
      {
        "modernName": "克拉玛依市",
        "ancientName": "克拉玛依"
      },
      {
        "modernName": "吐鲁番市",
        "ancientName": "高昌"
      },
      {
        "modernName": "哈密市",
        "ancientName": "伊州"
      },
      {
        "modernName": "昌吉回族自治州",
        "ancientName": "昌吉"
      },
      {
        "modernName": "博尔塔拉蒙古自治州",
        "ancientName": "博乐"
      },
      {
        "modernName": "巴音郭楞蒙古自治州",
        "ancientName": "库尔勒"
      },
      {
        "modernName": "阿克苏地区",
        "ancientName": "姑墨"
      },
      {
        "modernName": "克孜勒苏柯尔克孜自治州",
        "ancientName": "阿图什"
      },
      {
        "modernName": "喀什地区",
        "ancientName": "疏勒"
      },
      {
        "modernName": "和田地区",
        "ancientName": "于阗"
      },
      {
        "modernName": "伊犁哈萨克自治州",
        "ancientName": "伊犁"
      },
      {
        "modernName": "塔城地区",
        "ancientName": "塔尔巴哈台"
      },
      {
        "modernName": "阿勒泰地区",
        "ancientName": "阿勒泰"
      }
    ]
  },
  {
    "name": "台湾",
    "fullName": "台湾省",
    "sortOrder": 31,
    "macroRegionId": "huadong",
    "cities": [
      {
        "modernName": "台北市",
        "ancientName": "台北府"
      },
      {
        "modernName": "新北市",
        "ancientName": "板桥"
      },
      {
        "modernName": "桃园市",
        "ancientName": "桃园"
      },
      {
        "modernName": "台中市",
        "ancientName": "大墩"
      },
      {
        "modernName": "台南市",
        "ancientName": "府城"
      },
      {
        "modernName": "高雄市",
        "ancientName": "打狗"
      },
      {
        "modernName": "基隆市",
        "ancientName": "鸡笼"
      },
      {
        "modernName": "新竹市",
        "ancientName": "竹堑"
      },
      {
        "modernName": "嘉义市",
        "ancientName": "诸罗"
      },
      {
        "modernName": "新竹县",
        "ancientName": "新竹"
      },
      {
        "modernName": "苗栗县",
        "ancientName": "苗栗"
      },
      {
        "modernName": "彰化县",
        "ancientName": "彰化"
      },
      {
        "modernName": "南投县",
        "ancientName": "南投"
      },
      {
        "modernName": "云林县",
        "ancientName": "云林"
      },
      {
        "modernName": "嘉义县",
        "ancientName": "诸罗"
      },
      {
        "modernName": "屏东县",
        "ancientName": "阿猴"
      },
      {
        "modernName": "宜兰县",
        "ancientName": "噶玛兰"
      },
      {
        "modernName": "花莲县",
        "ancientName": "花莲"
      },
      {
        "modernName": "台东县",
        "ancientName": "卑南"
      },
      {
        "modernName": "澎湖县",
        "ancientName": "澎湖"
      },
      {
        "modernName": "金门县",
        "ancientName": "金门"
      },
      {
        "modernName": "连江县",
        "ancientName": "马祖"
      }
    ]
  },
  {
    "name": "香港",
    "fullName": "香港特别行政区",
    "sortOrder": 32,
    "macroRegionId": "huanan",
    "cities": [
      {
        "modernName": "香港特别行政区",
        "ancientName": "香江"
      }
    ]
  },
  {
    "name": "澳门",
    "fullName": "澳门特别行政区",
    "sortOrder": 33,
    "macroRegionId": "huanan",
    "cities": [
      {
        "modernName": "澳门特别行政区",
        "ancientName": "濠镜"
      }
    ]
  }
]
;
