# -*- coding: utf-8 -*-
"""Export province/city atlas seed for grand-tour store."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / "scripts" / "gen-city-ancient-names.py"
OUT = ROOT / "lib" / "city-atlas-seed.ts"

# 省级 fullName → 七大区 id（与 lib/city-macro-regions.ts 同步）
FULL_NAME_TO_MACRO: dict[str, str] = {
    "北京市": "huabei",
    "天津市": "huabei",
    "河北省": "huabei",
    "山西省": "huabei",
    "内蒙古自治区": "huabei",
    "辽宁省": "dongbei",
    "吉林省": "dongbei",
    "黑龙江省": "dongbei",
    "上海市": "huadong",
    "江苏省": "huadong",
    "浙江省": "huadong",
    "安徽省": "huadong",
    "福建省": "huadong",
    "江西省": "huadong",
    "山东省": "huadong",
    "台湾省": "huadong",
    "河南省": "huazhong",
    "湖北省": "huazhong",
    "湖南省": "huazhong",
    "广东省": "huanan",
    "广西壮族自治区": "huanan",
    "海南省": "huanan",
    "香港特别行政区": "huanan",
    "澳门特别行政区": "huanan",
    "重庆市": "xinan",
    "四川省": "xinan",
    "贵州省": "xinan",
    "云南省": "xinan",
    "西藏自治区": "xinan",
    "陕西省": "xibei",
    "甘肃省": "xibei",
    "青海省": "xibei",
    "宁夏回族自治区": "xibei",
    "新疆维吾尔自治区": "xibei",
}

spec = importlib.util.spec_from_file_location("gen_city", GEN)
gen = importlib.util.module_from_spec(spec)
assert spec.loader
spec.loader.exec_module(gen)

by_prov = gen.parse_wiki()
groups: list[dict] = []

for i, prov in enumerate(gen.PROVINCE_ORDER):
    short = gen.PROV_SHORT.get(prov, prov)
    cities: list[dict[str, str]] = []
    if prov in ("北京市", "天津市", "上海市", "重庆市"):
        m = dict(gen.MUNICIPALITIES)
        cities.append({"modernName": prov, "ancientName": m[prov]})
    elif prov == "台湾省":
        for city, anc in gen.TAIWAN:
            cities.append({"modernName": city, "ancientName": anc})
    elif prov == "香港特别行政区":
        cities.append({"modernName": "香港特别行政区", "ancientName": "香江"})
    elif prov == "澳门特别行政区":
        cities.append({"modernName": "澳门特别行政区", "ancientName": "濠镜"})
    else:
        for city in by_prov.get(prov, []):
            cities.append({"modernName": city, "ancientName": gen.ancient(city)})
    groups.append(
        {
            "name": short,
            "fullName": prov,
            "sortOrder": i,
            "macroRegionId": FULL_NAME_TO_MACRO.get(prov, "huabei"),
            "cities": cities,
        }
    )

lines = [
    "/** Auto-generated by scripts/export-city-atlas-seed.py — do not edit by hand. */",
    "",
    "export type CityAtlasSeedCity = { modernName: string; ancientName: string };",
    "export type CityAtlasSeedGroup = {",
    "  name: string;",
    "  fullName: string;",
    "  sortOrder: number;",
    "  macroRegionId: string;",
    "  cities: CityAtlasSeedCity[];",
    "};",
    "",
    "export const CITY_ATLAS_SEED: CityAtlasSeedGroup[] = ",
    json.dumps(groups, ensure_ascii=False, indent=2),
    ";",
    "",
]

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {OUT} ({len(groups)} provinces, {sum(len(g['cities']) for g in groups)} cities)")
